#!/bin/bash
# Crontab Setup for LARAI.VN
# Run this to install cron jobs

echo "================================"
echo "⏰ CRONTAB SETUP FOR LARAI.VN"
echo "================================"

# Create crontab entries
CRON_FILE="/tmp/coin87_crontab"

cat > $CRON_FILE << 'EOF'
# LARAI.VN Cron Jobs
# Generated by crontab_larai.sh

# ==========================================
# Database Backup - Daily at 2:00 AM
# ==========================================
0 2 * * * /home/coin87/coin87sourcev2/scripts/backup_db.sh >> /var/log/coin87/backup.log 2>&1

# ==========================================
# PM2 Save State - Every 6 hours (in case of manual changes)
# ==========================================
0 */6 * * * /usr/bin/pm2 save >> /var/log/coin87/pm2-save.log 2>&1

# ==========================================
# Log Rotation - Weekly on Sunday at 3:00 AM
# ==========================================
0 3 * * 0 find /var/log/coin87 -name "*.log" -mtime +7 -delete 2>&1

# ==========================================
# Cleanup old news - Daily at 4:00 AM (keep last 30 days)
# ==========================================
0 4 * * * cd /home/coin87/coin87sourcev2/backend && /home/coin87/coin87sourcev2/backend/venv/bin/python -c "from app.db.database import SessionLocal; from app.models.news import News; from datetime import datetime, timedelta; db = SessionLocal(); cutoff = datetime.now() - timedelta(days=30); db.query(News).filter(News.created_at < cutoff).delete(); db.commit(); db.close()" >> /var/log/coin87/cleanup.log 2>&1

# ==========================================
# Health Check & Alert - Every 15 minutes
# ==========================================
*/15 * * * * /home/coin87/coin87sourcev2/scripts/health_check.sh >> /var/log/coin87/health.log 2>&1

# ==========================================
# Restart PM2 processes if needed - Every hour
# ==========================================
0 * * * * /usr/bin/pm2 resurrect >> /dev/null 2>&1

EOF

# Install crontab
echo ""
echo "Installing crontab entries..."
crontab $CRON_FILE
rm $CRON_FILE

echo ""
echo "✅ Crontab installed successfully!"
echo ""
echo "Current crontab:"
crontab -l

echo ""
echo "================================"
echo "📋 Scheduled Tasks:"
echo "================================"
echo "✓ Database backup:     Daily at 2:00 AM"
echo "✓ PM2 save state:      Every 6 hours"
echo "✓ Log rotation:        Weekly (Sunday 3:00 AM)"
echo "✓ Cleanup old news:    Daily at 4:00 AM"
echo "✓ Health check:        Every 15 minutes"
echo "✓ PM2 resurrect:       Every hour"
echo ""
echo "View logs:"
echo "  tail -f /var/log/coin87/backup.log"
echo "  tail -f /var/log/coin87/health.log"
echo "================================"
